use master
go
if exists (select * from sysdatabases where name='QUANLYBANTHUOC')
	drop database QUANLYBANTHUOC
go
create database QUANLYBANTHUOC
on primary
(
	name= QUANLYBANTHUOCdat,
	filename='D:\QUANLYBANTHUOCdat.mdf',
	size=10, 
	maxsize=100,
	filegrowth=10
)
log on
(
	name=QUANLYBANTHUOClog,
	filename='D:\QUANLYBANTHUOClog.ldf',
	size=1,
	filegrowth=5
)
GO
use QUANLYBANTHUOC
CREATE TABLE CHUCVU
(
	MACHUCVU VARCHAR(20) PRIMARY KEY,
	MOTA NVARCHAR(100)
)
GO
CREATE TABLE NHANVIEN
(
	MANHANVIEN VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(100) NOT NULL,
	GIOITINH BINARY,
	SDT VARCHAR(15),
	EMAIL NVARCHAR(50),
	DANTOC	NVARCHAR(50),
	TONGIAO NVARCHAR(50),
	CMTND VARCHAR(20),
	NGAYCAP VARCHAR(10),
	NOICAP VARCHAR(50),
	NGAYBATDAUVAOLAM VARCHAR(10),
	MUCLUONG FLOAT,
	GHICHU NVARCHAR(100),
	MACHUCVU VARCHAR(20) FOREIGN KEY REFERENCES CHUCVU(MACHUCVU),
	TAIKHOAN NVARCHAR(50) NOT NULL,
	MATKHAU NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE CHUCNANG
(
	MACHUCNANG VARCHAR(100) PRIMARY KEY,
	MOTA NVARCHAR(100)
)
GO
CREATE TABLE PHANQUYEN
(
	MAPHANQUYEN VARCHAR(20),
	MACHUCVU VARCHAR(20) FOREIGN KEY REFERENCES CHUCVU(MACHUCVU),
	MACHUCNANG VARCHAR(100) FOREIGN KEY REFERENCES CHUCNANG(MACHUCNANG),
	XEM BINARY NOT NULL,
	THEM BINARY NOT NULL,
	SUA BINARY NOT NULL,
	XOA BINARY NOT NULL
)
GO